name: EnhancedHealth
author: FoodCans
version: ${project.version}
main: dev.foodcans.enhancedhealth.EnhancedHealth
api-version: 1.13
libraries: [ 'com.zaxxer:HikariCP:4.0.3', 'com.google.code.gson:gson:2.8.8' ]
commands:
  health:
    description: Manage player health data
