name: EnhancedHealth
author: FoodCans
version: ${project.version}
api-version: 1.17
main: dev.foodcans.enhancedhealth.EnhancedHealth
softdepend: [PlaceholderAPI]
libraries: [com.zaxxer:HikariCP:4.0.3, com.google.code.gson:gson:2.8.8]
commands:
  health: {}
